name: Royals Web - Qa

on:
  push:
    branches:
      - "main"

jobs:
  depl:
    uses: ./.github/workflows/google-cloudrun-common.yml
    with:
      NUXT_PUBLIC_DIRECTUS_URL: https://enrichment-center.dev.ds.dumont.de
      NUXT_DIRECTUS_API_TOKEN: 5n65w3aaMFUMqL52y6owV5AQoXfHQXfQ
      STRAPI_URL: https://ai-verticals-strapi-ktmjadcfsa-ey.a.run.app
      NUXT_PUBLIC_BLOG_URL: https://royals-verticals-web-qa-bnztxch5lq-ey.a.run.app
      ENV: qa
      MANDATOR: royals
      NUXT_DEPLOYMENT_HASH: ${{ github.sha }}
      SERVICE: royals-verticals-web-qa
      PROJECT_ID: dmx-case42
      CICD_GCLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/734680744363/locations/global/workloadIdentityPools/github-pool/providers/github-pool
      CICD_GCLOUD_SERVICE_ACCOUNT: github-ksta-medien@dmx-case42.iam.gserviceaccount.com
